name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PDFs
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: "*.pdf"
